### ISSUE TITLE
Exposing class definitions to Lua

### ISSUE THREAD

**Issue by ProtectedMode** [tomaka/luawrapper#2]
There should be a way to expose classes to the Lua state, that can be instantiated from Lua. An extra option could be to allow passing these custom types as parameters or using them as return type without hacks.

**Comment by facontidavide** [comment]
Suggestion. Add this to the documentation. I had the same "problem".

**Comment by 0X1A** [comment]
@facontidavide This 'fork' is no longer being maintained. There's a link to one that is but they do not have an open issue tracker.
